// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by sqlc_dart

part of 'sqlc.dart';

class Queries {
  final Database _db;

  Queries(this._db);

  // InsertUser
  Future<User> insertUser(String name, String username, String email, String password) async {
    const sql = r'''INSERT INTO
    users (
        name,
        username,
        email,
        password
    )
VALUES (?, ?, ?, ?)
RETURNING
    id, name, username, email, password, created_at, updated_at''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([name, username, email, password]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query insertUser');
      }
      final row = result.first;
      return User.fromMap(row);
    } catch (e) {
      if (e is SqlcException) rethrow;
      throw SqlcException('Error executing query insertUser', e);
    } finally {
      stmt.close();
    }
  }

  // GetUserById
  Future<User> getUserById(int id) async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users WHERE id = ? LIMIT 1''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([id]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query getUserById');
      }
      final row = result.first;
      return User.fromMap(row);
    } catch (e) {
      if (e is SqlcException) rethrow;
      throw SqlcException('Error executing query getUserById', e);
    } finally {
      stmt.close();
    }
  }

  // GetUserByUsername
  Future<User> getUserByUsername(String username) async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users WHERE username = ? LIMIT 1''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([username]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query getUserByUsername');
      }
      final row = result.first;
      return User.fromMap(row);
    } catch (e) {
      if (e is SqlcException) rethrow;
      throw SqlcException('Error executing query getUserByUsername', e);
    } finally {
      stmt.close();
    }
  }

  // GetUserByEmail
  Future<User> getUserByEmail(String email) async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users WHERE email = ? LIMIT 1''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([email]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query getUserByEmail');
      }
      final row = result.first;
      return User.fromMap(row);
    } catch (e) {
      if (e is SqlcException) rethrow;
      throw SqlcException('Error executing query getUserByEmail', e);
    } finally {
      stmt.close();
    }
  }

  // ListUsers
  Future<List<User>> listUsers() async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users ORDER BY name''';
    try {
      final result = _db.select(sql);
      return result.map((row) => User.fromMap(row)).toList();
    } catch (e) {
      throw SqlcException('Error executing query listUsers', e);
    }
  }

  // UpdateUser
  Future<void> updateUser(String name, String username, String email, String password, int id) async {
    const sql = r'''UPDATE users
set
    name = ?,
    username = ?,
    email = ?,
    password = ?
WHERE
    id = ?''';
    final stmt = _db.prepare(sql);
    try {
      stmt.execute([name, username, email, password, id]);
    } catch (e) {
      throw SqlcException('Error executing query updateUser', e);
    } finally {
      stmt.close();
    }
  }

  // DeleteUser
  Future<void> deleteUser(int id) async {
    const sql = r'''DELETE FROM users WHERE id = ?''';
    final stmt = _db.prepare(sql);
    try {
      stmt.execute([id]);
    } catch (e) {
      throw SqlcException('Error executing query deleteUser', e);
    } finally {
      stmt.close();
    }
  }

}
