// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by sqlc_dart

part of 'sqlc.dart';

class Queries {
  final Database _db;

  Queries(this._db);

  // GetAuthor
  static const String getauthorSql = r'''SELECT id, name, bio FROM authors WHERE id = $1 LIMIT 1''';

  Authors? getauthor(int id) {
    final stmt = _db.prepare(getauthorSql);
    try {
      final result = stmt.select([id]);
      if (result.isEmpty) return null;
      final row = result.first;
      return Authors.fromMap(row);
    } catch (e) {
      throw SqlcException('Error executing query getauthor', e);
    } finally {
      stmt.close();
    }
  }

  // ListAuthors
  static const String listauthorsSql = r'''SELECT id, name, bio FROM authors ORDER BY name''';

  List<Authors> listauthors() {
    try {
      final result = _db.select(listauthorsSql);
      return result.map((row) => Authors.fromMap(row)).toList();
    } catch (e) {
      throw SqlcException('Error executing query listauthors', e);
    }
  }

  // CreateAuthor
  static const String createauthorSql = r'''INSERT INTO authors (name, bio) VALUES ($1, $2) RETURNING id, name, bio''';

  Authors? createauthor(String name, String? bio) {
    final stmt = _db.prepare(createauthorSql);
    try {
      final result = stmt.select([name, bio]);
      if (result.isEmpty) return null;
      final row = result.first;
      return Authors.fromMap(row);
    } catch (e) {
      throw SqlcException('Error executing query createauthor', e);
    } finally {
      stmt.close();
    }
  }

  // UpdateAuthor
  static const String updateauthorSql = r'''UPDATE authors set name = $2, bio = $3 WHERE id = $1''';

  void updateauthor(int id, String name, String? bio) {
    final stmt = _db.prepare(updateauthorSql);
    try {
      stmt.execute([id, name, bio]);
    } catch (e) {
      throw SqlcException('Error executing query updateauthor', e);
    } finally {
      stmt.close();
    }
  }

  // DeleteAuthor
  static const String deleteauthorSql = r'''DELETE FROM authors WHERE id = $1''';

  void deleteauthor(int id) {
    final stmt = _db.prepare(deleteauthorSql);
    try {
      stmt.execute([id]);
    } catch (e) {
      throw SqlcException('Error executing query deleteauthor', e);
    } finally {
      stmt.close();
    }
  }

}

