// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by sqlc_dart

part of 'sqlc_dart.dart';

class Queries {
  // GetAuthor
  static const String getauthorSql = r'''SELECT id, name, bio FROM authors WHERE id = $1 LIMIT 1''';

  Authors getauthor(int id) {
    // TODO: Implement query execution
    throw UnimplementedError('Query execution not implemented');
  }

  // ListAuthors
  static const String listauthorsSql = r'''SELECT id, name, bio FROM authors ORDER BY name''';

  List<Authors> listauthors() {
    // TODO: Implement query execution
    throw UnimplementedError('Query execution not implemented');
  }

  // CreateAuthor
  static const String createauthorSql = r'''INSERT INTO authors (name, bio) VALUES ($1, $2) RETURNING id, name, bio''';

  Authors createauthor(String name, String? bio) {
    // TODO: Implement query execution
    throw UnimplementedError('Query execution not implemented');
  }

  // UpdateAuthor
  static const String updateauthorSql = r'''UPDATE authors set name = $2, bio = $3 WHERE id = $1''';

  void updateauthor(int id, String name, String? bio) {
    // TODO: Implement query execution
    throw UnimplementedError('Query execution not implemented');
  }

  // DeleteAuthor
  static const String deleteauthorSql = r'''DELETE FROM authors WHERE id = $1''';

  void deleteauthor(int id) {
    // TODO: Implement query execution
    throw UnimplementedError('Query execution not implemented');
  }

}

