// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by sqlc_dart

part of 'sqlc_dart.dart';

class Authors {
  final int id;
  final String name;
  final String? bio;

  Authors({required this.id, required this.name, this.bio});

  factory Authors.fromMap(Map<String, dynamic> map) {
    return Authors(
      id: map['id'] as int,
      name: map['name'] as String,
      bio: map['bio'] as String?,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'bio': bio,
    };
  }
}


