// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by sqlc_dart

import 'package:sqlite3/sqlite3.dart';

/// Configuration for SQLite database
sealed class SqliteConfig {}

/// In-memory SQLite database
class SqliteMemory extends SqliteConfig {}

/// File-based SQLite database
class SqliteLocal extends SqliteConfig {
  final String path;
  SqliteLocal(this.path);
}

/// Custom exception for SQLC generated code
class SqlcException implements Exception {
  final String message;
  final Object? originalError;
  SqlcException(this.message, [this.originalError]);
  @override
  String toString() => 'SqlcException: $message ${originalError != null ? "($originalError)" : ""}';
}

/// Main class for managing database connection and queries
class Sqlc {
  final Database _db;
  late final Queries queries;

  Sqlc._(this._db) {
    queries = Queries(_db);
  }

  /// Create a new Sqlc instance with the given configuration
  factory Sqlc(SqliteConfig config) {
    final db = switch (config) {
      SqliteMemory() => sqlite3.openInMemory(),
      SqliteLocal(:final path) => sqlite3.open(path),
    };
    return Sqlc._(db);
  }

  /// Close the database connection
  void close() => _db.close();

  /// Get the underlying database instance
  Database get database => _db;
}

class User {
  final int id;
  final String name;
  final String username;
  final String email;
  final String password;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  User({required this.id, required this.name, required this.username, required this.email, required this.password, this.createdAt, this.updatedAt});

  factory User.fromMap(Map<String, dynamic> map) {
    return User(
      id: map['id'] as int,
      name: map['name'] as String,
      username: map['username'] as String,
      email: map['email'] as String,
      password: map['password'] as String,
      createdAt: map['created_at'] != null ? DateTime.parse(map['created_at'] as String) : null,
      updatedAt: map['updated_at'] != null ? DateTime.parse(map['updated_at'] as String) : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'username': username,
      'email': email,
      'password': password,
      'created_at': createdAt?.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }
}

class Chat {
  final int id;
  final String? name;
  final String type;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  Chat({required this.id, this.name, required this.type, this.createdAt, this.updatedAt});

  factory Chat.fromMap(Map<String, dynamic> map) {
    return Chat(
      id: map['id'] as int,
      name: map['name'] as String?,
      type: map['type'] as String,
      createdAt: map['created_at'] != null ? DateTime.parse(map['created_at'] as String) : null,
      updatedAt: map['updated_at'] != null ? DateTime.parse(map['updated_at'] as String) : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'type': type,
      'created_at': createdAt?.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }
}

class Participant {
  final int userId;
  final int chatId;
  final DateTime? createdAt;

  Participant({required this.userId, required this.chatId, this.createdAt});

  factory Participant.fromMap(Map<String, dynamic> map) {
    return Participant(
      userId: map['user_id'] as int,
      chatId: map['chat_id'] as int,
      createdAt: map['created_at'] != null ? DateTime.parse(map['created_at'] as String) : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'user_id': userId,
      'chat_id': chatId,
      'created_at': createdAt?.toIso8601String(),
    };
  }
}

class Message {
  final int id;
  final int chatId;
  final int userId;
  final String content;
  final String type;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  Message({required this.id, required this.chatId, required this.userId, required this.content, required this.type, this.createdAt, this.updatedAt});

  factory Message.fromMap(Map<String, dynamic> map) {
    return Message(
      id: map['id'] as int,
      chatId: map['chat_id'] as int,
      userId: map['user_id'] as int,
      content: map['content'] as String,
      type: map['type'] as String,
      createdAt: map['created_at'] != null ? DateTime.parse(map['created_at'] as String) : null,
      updatedAt: map['updated_at'] != null ? DateTime.parse(map['updated_at'] as String) : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'chat_id': chatId,
      'user_id': userId,
      'content': content,
      'type': type,
      'created_at': createdAt?.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }
}

class Queries {
  final Database _db;

  Queries(this._db);

  // InsertUser
  Future<User> insertUser(String name, String username, String email, String password) async {
    const sql = r'''INSERT INTO
    users (
        name,
        username,
        email,
        password
    )
VALUES (?, ?, ?, ?)
RETURNING
    id, name, username, email, password, created_at, updated_at''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([name, username, email, password]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query insertUser');
      }
      final row = result.first;
      return User.fromMap(row);
    } catch (e) {
      if (e is SqlcException) rethrow;
      throw SqlcException('Error executing query insertUser', e);
    } finally {
      stmt.close();
    }
  }

  // GetUserById
  Future<User> getUserById(int id) async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users WHERE id = ? LIMIT 1''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([id]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query getUserById');
      }
      final row = result.first;
      return User.fromMap(row);
    } catch (e) {
      if (e is SqlcException) rethrow;
      throw SqlcException('Error executing query getUserById', e);
    } finally {
      stmt.close();
    }
  }

  // GetUserByUsername
  Future<User> getUserByUsername(String username) async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users WHERE username = ? LIMIT 1''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([username]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query getUserByUsername');
      }
      final row = result.first;
      return User.fromMap(row);
    } catch (e) {
      if (e is SqlcException) rethrow;
      throw SqlcException('Error executing query getUserByUsername', e);
    } finally {
      stmt.close();
    }
  }

  // GetUserByEmail
  Future<User> getUserByEmail(String email) async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users WHERE email = ? LIMIT 1''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([email]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query getUserByEmail');
      }
      final row = result.first;
      return User.fromMap(row);
    } catch (e) {
      if (e is SqlcException) rethrow;
      throw SqlcException('Error executing query getUserByEmail', e);
    } finally {
      stmt.close();
    }
  }

  // ListUsers
  Future<List<User>> listUsers() async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users ORDER BY name''';
    try {
      final result = _db.select(sql);
      return result.map((row) => User.fromMap(row)).toList();
    } catch (e) {
      throw SqlcException('Error executing query listUsers', e);
    }
  }

  // UpdateUser
  Future<void> updateUser(String name, String username, String email, String password, int id) async {
    const sql = r'''UPDATE users
set
    name = ?,
    username = ?,
    email = ?,
    password = ?
WHERE
    id = ?''';
    final stmt = _db.prepare(sql);
    try {
      stmt.execute([name, username, email, password, id]);
    } catch (e) {
      throw SqlcException('Error executing query updateUser', e);
    } finally {
      stmt.close();
    }
  }

  // DeleteUser
  Future<void> deleteUser(int id) async {
    const sql = r'''DELETE FROM users WHERE id = ?''';
    final stmt = _db.prepare(sql);
    try {
      stmt.execute([id]);
    } catch (e) {
      throw SqlcException('Error executing query deleteUser', e);
    } finally {
      stmt.close();
    }
  }

}
