// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by sqlc_dart

import 'package:sqlite3/sqlite3.dart';

part 'schema.dart';
part 'queries.dart';

/// Configuration for SQLite database
sealed class SqliteConfig {}

/// In-memory SQLite database
class SqliteMemory extends SqliteConfig {}

/// File-based SQLite database
class SqliteLocal extends SqliteConfig {
  final String path;
  SqliteLocal(this.path);
}

/// Custom exception for SQLC generated code
class SqlcException implements Exception {
  final String message;
  final Object? originalError;
  SqlcException(this.message, [this.originalError]);
  @override
  String toString() => 'SqlcException: $message ${originalError != null ? "($originalError)" : ""}';
}

/// Main class for managing database connection and queries
class Sqlc {
  final Database _db;
  late final Queries queries;

  Sqlc._(this._db) {
    queries = Queries(_db);
  }

  /// Create a new Sqlc instance with the given configuration
  factory Sqlc(SqliteConfig config) {
    final db = switch (config) {
      SqliteMemory() => sqlite3.openInMemory(),
      SqliteLocal(:final path) => sqlite3.open(path),
    };
    return Sqlc._(db);
  }

  /// Close the database connection
  void close() => _db.close();

  /// Get the underlying database instance
  Database get database => _db;
}


