// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by sqlc_dart

import 'package:sqlite3/sqlite3.dart';

/// Custom exception for SQLC generated code
class SqlcException implements Exception {
  final String message;
  final Object? originalError;
  SqlcException(this.message, [this.originalError]);
  @override
  String toString() => 'SqlcException: $message ${originalError != null ? "($originalError)" : ""}';
}

/// Configuration for SQLite database
sealed class SqliteConfig {}

/// In-memory SQLite database
class SqliteMemory extends SqliteConfig {}

/// File-based SQLite database
class SqliteLocal extends SqliteConfig {
  final String path;
  SqliteLocal(this.path);
}

/// Main class for managing database connection and queries
class SqlcDart {
  late final Queries queries;

  SqlcDart(SqliteConfig config) {
    final db = switch (config) {
      SqliteMemory() => sqlite3.openInMemory(),
      SqliteLocal(:final path) => sqlite3.open(path),
    };
    queries = Queries(db);
  }
}

class User {
  final int id;
  final String name;
  final String username;
  final String email;
  final String password;
  final DateTime createdAt;
  final DateTime updatedAt;

  const User({required this.id, required this.name, required this.username, required this.email, required this.password, required this.createdAt, required this.updatedAt});

  factory User.fromMap(Map<String, dynamic> map) {
    return User(
      id: map['id'] as int,
      name: map['name'] as String,
      username: map['username'] as String,
      email: map['email'] as String,
      password: map['password'] as String,
      createdAt: DateTime.parse(map['created_at'] as String),
      updatedAt: DateTime.parse(map['updated_at'] as String),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'username': username,
      'email': email,
      'password': password,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}

class Chat {
  final int id;
  final String? name;
  final String type;
  final int userId;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Chat({required this.id, this.name, required this.type, required this.userId, required this.createdAt, required this.updatedAt});

  factory Chat.fromMap(Map<String, dynamic> map) {
    return Chat(
      id: map['id'] as int,
      name: map['name'] as String?,
      type: map['type'] as String,
      userId: map['user_id'] as int,
      createdAt: DateTime.parse(map['created_at'] as String),
      updatedAt: DateTime.parse(map['updated_at'] as String),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'type': type,
      'user_id': userId,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}

class Participant {
  final int userId;
  final int chatId;
  final DateTime createdAt;

  const Participant({required this.userId, required this.chatId, required this.createdAt});

  factory Participant.fromMap(Map<String, dynamic> map) {
    return Participant(
      userId: map['user_id'] as int,
      chatId: map['chat_id'] as int,
      createdAt: DateTime.parse(map['created_at'] as String),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'user_id': userId,
      'chat_id': chatId,
      'created_at': createdAt.toIso8601String(),
    };
  }
}

class Message {
  final int id;
  final int chatId;
  final int userId;
  final String content;
  final String type;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Message({required this.id, required this.chatId, required this.userId, required this.content, required this.type, required this.createdAt, required this.updatedAt});

  factory Message.fromMap(Map<String, dynamic> map) {
    return Message(
      id: map['id'] as int,
      chatId: map['chat_id'] as int,
      userId: map['user_id'] as int,
      content: map['content'] as String,
      type: map['type'] as String,
      createdAt: DateTime.parse(map['created_at'] as String),
      updatedAt: DateTime.parse(map['updated_at'] as String),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'chat_id': chatId,
      'user_id': userId,
      'content': content,
      'type': type,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}

class Queries {
  final Database _db;

  Queries(this._db);

  Future<User> insertUser({required String name, required String username, required String email, required String password}) async {
    const sql = r'''INSERT INTO
    users (
        name,
        username,
        email,
        password
    )
VALUES (?, ?, ?, ?)
RETURNING
    id, name, username, email, password, created_at, updated_at''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([name, username, email, password]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query insertUser');
      }
      final row = result.first;
      return User.fromMap(row);
    } on SqlcException {
      rethrow;
    } on SqliteException catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } on Exception catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } finally {
      stmt.close();
    }
  }

  Future<User> getUserById({required int id}) async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users WHERE id = ? LIMIT 1''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([id]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query getUserById');
      }
      final row = result.first;
      return User.fromMap(row);
    } on SqlcException {
      rethrow;
    } on SqliteException catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } on Exception catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } finally {
      stmt.close();
    }
  }

  Future<User> getUserByUsername({required String username}) async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users WHERE username = ? LIMIT 1''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([username]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query getUserByUsername');
      }
      final row = result.first;
      return User.fromMap(row);
    } on SqlcException {
      rethrow;
    } on SqliteException catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } on Exception catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } finally {
      stmt.close();
    }
  }

  Future<User> getUserByEmail({required String email}) async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users WHERE email = ? LIMIT 1''';
    final stmt = _db.prepare(sql);
    try {
      final result = stmt.select([email]);
      if (result.isEmpty) {
        throw SqlcException('No results found for query getUserByEmail');
      }
      final row = result.first;
      return User.fromMap(row);
    } on SqlcException {
      rethrow;
    } on SqliteException catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } on Exception catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } finally {
      stmt.close();
    }
  }

  Future<List<User>> listUsers() async {
    const sql = r'''SELECT id, name, username, email, password, created_at, updated_at FROM users ORDER BY name''';
    try {
      final result = _db.select(sql);
      return result.map((row) => User.fromMap(row)).toList();
    } on SqlcException {
      rethrow;
    } on SqliteException catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } on Exception catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    }
  }

  Future<void> updateUser({required String name, required String username, required String email, required String password, required int id}) async {
    const sql = r'''UPDATE users
set
    name = coalesce(?, name),
    username = coalesce(?, username),
    email = coalesce(?, email),
    password = coalesce(?, password)
WHERE
    id = ?''';
    final stmt = _db.prepare(sql);
    try {
      stmt.execute([name, username, email, password, id]);
    } on SqlcException {
      rethrow;
    } on SqliteException catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } on Exception catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } finally {
      stmt.close();
    }
  }

  Future<void> deleteUser({required int id}) async {
    const sql = r'''DELETE FROM users WHERE id = ?''';
    final stmt = _db.prepare(sql);
    try {
      stmt.execute([id]);
    } on SqlcException {
      rethrow;
    } on SqliteException catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } on Exception catch (e) {
      throw SqlcException(e.runtimeType.toString(), e);
    } finally {
      stmt.close();
    }
  }

}
