// GENERATED BY sqlc-gen-dart
class Queries {
  // Query: GetAuthor
  String get GetAuthorQuery => r"""SELECT id, name, bio FROM authors WHERE id = $1 LIMIT 1""";

  // Query: ListAuthors
  String get ListAuthorsQuery => r"""SELECT id, name, bio FROM authors ORDER BY name""";

  // Query: CreateAuthor
  String get CreateAuthorQuery => r"""INSERT INTO authors (name, bio) VALUES ($1, $2) RETURNING id, name, bio""";

  // Query: UpdateAuthor
  String get UpdateAuthorQuery => r"""UPDATE authors set name = $2, bio = $3 WHERE id = $1""";

  // Query: DeleteAuthor
  String get DeleteAuthorQuery => r"""DELETE FROM authors WHERE id = $1""";
}
