library;

import 'dart:convert';

Future<String> generateFromSqlcInput(String jsonInput) async {
  final data = Map<String, dynamic>.from(jsonDecode(jsonInput));

  final request = CodeGenRequest.fromJson(data);

  final files = DartCodeGenerator().generate(request);

  final response = CodeGenResponse(files: files);

  return jsonEncode(response.toJson());
}

class CodeGenRequest {
  final List<SqlcQuery> queries;

  CodeGenRequest({required this.queries});

  factory CodeGenRequest.fromJson(Map<String, dynamic> json) {
    return CodeGenRequest(
      queries: (json['queries'] as List<dynamic>? ?? []).map((e) => SqlcQuery.fromJson(e)).toList(),
    );
  }
}

class SqlcQuery {
  final String name;
  final String text;

  SqlcQuery({required this.name, required this.text});

  factory SqlcQuery.fromJson(Map<String, dynamic> json) {
    return SqlcQuery(name: json['name'] ?? '', text: json['text'] ?? '');
  }
}

class GeneratedFile {
  final String name;
  final String contents;

  GeneratedFile({required this.name, required this.contents});

  Map<String, dynamic> toJson() => {'name': name, 'contents': base64Encode(utf8.encode(contents))};
}

class CodeGenResponse {
  final List<GeneratedFile> files;

  CodeGenResponse({required this.files});

  Map<String, dynamic> toJson() => {'files': files.map((e) => e.toJson()).toList()};
}

class DartCodeGenerator {
  List<GeneratedFile> generate(CodeGenRequest request) {
    final buffer = StringBuffer();

    buffer.writeln("// GENERATED BY sqlc_dart");
    buffer.writeln("// DO NOT MODIFY THIS FILE");
    buffer.writeln("");
    buffer.writeln("class Queries {");

    for (final q in request.queries) {
      buffer.writeln(templateQueryMethod(q.name, q.text));
    }

    buffer.writeln("}");

    return [GeneratedFile(name: "sqlc_queries.g.dart", contents: buffer.toString())];
  }
}

String templateQueryMethod(String name, String sql) {
  return '''
  // Query: $name
  String get ${name}Query => r"""$sql""";
  ''';
}
